# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\code\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QDesktopServices
from PyQt5.QtWidgets import (
    QApplication,
    QLabel,
    QLineEdit,
    QMessageBox,
    QVBoxLayout,
    QWidget,
)


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(734, 546)  # 主窗口大小
        self.login = QtWidgets.QPushButton(main_window)
        self.login.setGeometry(QtCore.QRect(180, 340, 131, 51))  # 登录按钮大小位置
        self.login.setObjectName("login")
        self.account = QtWidgets.QLineEdit(main_window)
        self.account.setGeometry(QtCore.QRect(170, 140, 411, 31))  # 账号输入框大小位置
        self.account.setObjectName("account")
        self.password = QtWidgets.QLineEdit(main_window)
        self.password.setGeometry(QtCore.QRect(170, 220, 411, 31))  # 密码输入框大小位置
        self.password.setObjectName("password")
        self.password.setEchoMode(QLineEdit.Password)
        self.regestier = QtWidgets.QPushButton(main_window)
        self.regestier.setGeometry(QtCore.QRect(400, 340, 141, 51))  # 注册按钮大小位置
        self.regestier.setObjectName("regestier")
        
        self.label1 = QLabel(main_window)

        self.retranslateUi(main_window)  # 文本翻译
        QtCore.QMetaObject.connectSlotsByName(main_window)  # 自动连接solt

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "用户登录"))
        self.login.setText(_translate("main_window", "登录"))
        self.account.setPlaceholderText(_translate("main_window", "输入学号"))
        self.password.setPlaceholderText(_translate("main_window", "输入密码"))
        self.regestier.setText(_translate("main_window", "注册"))


class main_window(QtWidgets.QMainWindow, Ui_main_window):
    def __init__(self):
        super(main_window, self).__init__()
        self.setupUi(self)
        self.users = {}  # 储存用户信息

        self.login.clicked.connect(self.login_check)
        self.regestier.clicked.connect(self.regestier_check)

    # 登录方法
    def login_check(self):
        account = self.account.text()
        password = self.password.text()
        if account in self.users:
            if self.users[account] == password:
                self.open_homepage()
            else:
                QMessageBox.warning(self, "错误", "密码错误")
        else:
            QMessageBox.warning(self, "错误", "账号不存在")

    # 注册方法
    def regestier_check(self):
        account = self.account.text()
        password = self.password.text()
        if account in self.users:
            QMessageBox.warning(self, "错误", "该学号已注册")
        else:
            self.users[account] = password
            QMessageBox.information(self, "注册", "注册成功")

    # 打开网页
    def open_homepage(self):
        QDesktopServices.openUrl(QtCore.QUrl("http://www.hdu.edu.cn"))


if __name__ == "__main__":
    app = QApplication(sys.argv)
    main_window = main_window()
    main_window.show()
    sys.exit(app.exec_())
